const ROLES = {
  ADMIN: 'admin',
  USER: 'user',
};

const SCOPES = {
  DASHBOARD: 'DASHBOARD',
  POS: 'POS',
  CUSTOMER_DISPLAY: 'CUSTOMER_DISPLAY',
  KITCHEN_DISPLAY: 'KITCHEN_DISPLAY',
  ORDER_STATUS_DISPLAY: 'ORDER_STATUS_DISPLAY',
  ORDER_STATUS: 'ORDER_STATUS',
  ORDERS: 'ORDERS',
  KITCHEN: 'KITCHEN',
  RESERVATIONS: 'RESERVATIONS',
  VIEW_RESERVATIONS: 'VIEW_RESERVATIONS',
  MANAGE_RESERVATIONS: 'MANAGE_RESERVATIONS',
  CUSTOMERS: 'CUSTOMERS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  INVOICES: 'INVOICES',
  MEMBERSHIP: 'MEMBERSHIP',
  SETTINGS: 'SETTINGS',
  REPORTS: 'REPORTS',
  STOCK: 'STOCK',
  VIEW_STOCK: 'VIEW_STOCK',
  MANAGE_STOCK: 'MANAGE_STOCK',
};

exports.ROLES = ROLES;
exports.SCOPES = SCOPES;
